"""todo-models

Revision ID: 77ec4552553c
Revises: e5aec2143b83
Create Date: 2020-12-09 16:28:57.205582

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77ec4552553c"
down_revision = "e5aec2143b83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("dueto", sa.DateTime(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("focus", sa.Boolean(), nullable=False),
        sa.Column("folder", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["todo_item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todo_item")
    # ### end Alembic commands ###
