"""domain fields and update slug

Revision ID: 83226bace0db
Revises: cca49105cb46
Create Date: 2018-05-25 09:53:44.609128

"""
from urllib.parse import urlparse
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session as BaseSession
from slugify import slugify


# revision identifiers, used by Alembic.
revision = '83226bace0db'
down_revision = 'cca49105cb46'
branch_labels = None
depends_on = None

Session = sessionmaker()
Base = declarative_base()

class Bookmark(Base):
    __tablename__ = 'bookmark'

    id = sa.Column(sa.Integer, primary_key=True)
    url = sa.Column(sa.Text, nullable=False)
    title = sa.Column(sa.Text, nullable=False)
    slug = sa.Column(sa.Text, nullable=True)
    domain = sa.Column(sa.Text, nullable=True)

    @property
    def _slug(self):
        txt = ' '.join(filter(None, [
            self.title,
            self._domain,
        ]))
        return slugify(txt, separator=' ')

    @property
    def _domain(self):
        d = urlparse(self.url).netloc
        return d.strip('www.')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('domain', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)
    for b in session.query(Bookmark):
        b.slug = b._slug
        b.domain = b._domain
        session.add(b)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'domain')
    # ### end Alembic commands ###
