"""empty message

Revision ID: b18330f1a80a
Revises: 3dbc4aebf445
Create Date: 2018-05-22 16:38:41.302428

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b18330f1a80a"
down_revision = "3dbc4aebf445"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("readed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookmark")
    # ### end Alembic commands ###
