export default {
  ADD_ALERT: 'ADD_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',

  AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LINKS_REQUEST: 'LINKS_REQUEST',
  LINKS_SUCCESS: 'LINKS_SUCCESS',
  LINKS_FAILURE: 'LINKS_FAILURE',

  EVENTS_SELECT_MONTH: 'EVENTS_SELECT_MONTH',
  EVENTS_REQUEST: 'EVENTS_REQUEST',
  EVENTS_SUCCESS: 'EVENTS_SUCCESS',
  EVENTS_FAILURE: 'EVENTS_FAILURE',
};
