export default {
  ADD_ALERT: 'ADD_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',

  AUTH_PRELOAD: 'AUTH_PRELOAD',
  AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  LINKS_REQUEST: 'LINKS_REQUEST',
  LINKS_SUCCESS: 'LINKS_SUCCESS',
  LINKS_FAILURE: 'LINKS_FAILURE',
  LINKS_FILTER: 'LINKS_FILTER',

  EVENTS_SELECT_MONTH: 'EVENTS_SELECT_MONTH',
  EVENTS_SHOW_EDIT: 'EVENTS_SHOW_EDIT',
  EVENTS_SHOW_EDIT_NEW: 'EVENTS_SHOW_EDIT_NEW',
  EVENTS_HIDE_EDIT: 'EVENTS_HIDE_EDIT',
  EVENTS_NEW_REQUEST: 'EVENTS_NEW_REQUEST',
  EVENTS_NEW_SUCCESS: 'EVENTS_NEW_SUCCESS',
  EVENTS_NEW_FAILURE: 'EVENTS_NEW_FAILURE',
  EVENTS_EDIT_REQUEST: 'EVENTS_EDIT_REQUEST',
  EVENTS_EDIT_SUCCESS: 'EVENTS_EDIT_SUCCESS',
  EVENTS_EDIT_FAILURE: 'EVENTS_EDIT_FAILURE',
  EVENTS_REQUEST: 'EVENTS_REQUEST',
  EVENTS_SUCCESS: 'EVENTS_SUCCESS',
  EVENTS_FAILURE: 'EVENTS_FAILURE',
};
